name: maisxbox
description: Site Mais Xbox
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl:
  cupertino_icons: ^1.0.3
  firebase_core: ^1.3.0
  firebase_crashlytics: ^2.0.7
  firebase_analytics: ^8.1.2
  firebase_remote_config: ^0.10.0+2
  cloud_firestore: ^2.5.0
  http: ^0.13.3
  get_it: ^7.2.0
  equatable: ^2.0.3
  connectivity: ^3.0.6
  another_flushbar: ^1.10.24
  flutter_spinkit: ^5.0.0
  cached_network_image: ^3.0.0
  uuid: ^3.0.4
  shared_preferences: ^2.0.7
  json_annotation: ^4.0.1
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0
  package_info: ^2.0.2
  device_info: ^2.0.2
  built_collection: ^5.1.0
  mask_text_input_formatter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  build_runner: ^2.0.4
  json_serializable: ^4.1.3
  mobx_codegen: ^2.0.1+3 #flutter pub run build_runner watch --delete-conflicting-outputs
  html: ^0.15.0

flutter:
  uses-material-design: true

  # assets:
  #   - lib/presentation/ui/assets/images/
  #   - lib/presentation/ui/assets/images/logos/
  #   - lib/presentation/ui/assets/images/icons/

  # fonts:
  #   - family: CircularStd-Black
  #     fonts:
  #       - asset: lib/presentation/ui/assets/fonts/CircularStd-Black.otf
  #       - asset: lib/presentation/ui/assets/fonts/CircularStd-BlackItalic.otf
  #         style: italic
  #       - asset: lib/presentation/ui/assets/fonts/CircularStd-Black.otf
  #         weight: 700
  #   - family: CircularStd-Bold
  #     fonts:
  #       - asset: lib/presentation/ui/assets/fonts/CircularStd-Bold.otf
  #       - asset: lib/presentation/ui/assets/fonts/CircularStd-BoldItalic.otf
  #         style: italic
  #       - asset: lib/presentation/ui/assets/fonts/CircularStd-Bold.otf
  #         weight: 700
  #   - family: CircularStd-Book
  #     fonts:
  #       - asset: lib/presentation/ui/assets/fonts/CircularStd-Book.otf
  #       - asset: lib/presentation/ui/assets/fonts/CircularStd-BookItalic.otf
  #         style: italic
  #       - asset: lib/presentation/ui/assets/fonts/CircularStd-Book.otf
  #         weight: 700
  #   - family: CircularStd-Medium
  #     fonts:
  #       - asset: lib/presentation/ui/assets/fonts/CircularStd-Medium.otf
  #       - asset: lib/presentation/ui/assets/fonts/CircularStd-MediumItalic.otf
  #         style: italic
  #       - asset: lib/presentation/ui/assets/fonts/CircularStd-Medium.otf
  #         weight: 700